language: node_js
os:
- osx
- linux
node_js:
- 8.6
env:
- ZMQ_DYNAMIC=false
- ZMQ_DYNAMIC=true

addons:
  apt:
    packages:
    - libzmq3-dev

before_install:
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update && brew install zeromq; fi

deploy:
  provider: script
  skip_cleanup: true
  script:
  - ./node_modules/prebuild/bin.js --target 8.6.0 --verbose --strip --upload ${GH_TOKEN}
  on:
    condition: "$ZMQ_DYNAMIC = false"
    tags: true
