language: node_js
os:
- osx
- linux
node_js:
- 8.6
env:
  matrix:
  - ZMQ_DYNAMIC=false
  - ZMQ_DYNAMIC=true
  global:
    secure: aLDkRNWCca4+djvfGfIktX2f4tp2/7dNjV8ByfWgPVoUA4Di6Ik7IiIEv5Q7yIFb4S7GZbTUUv3/Gilj6XqL/jL5YrtrB60CUu87ofPoOGpfqFg/MciPp6dj2m5Fz8+1GbY+0VvCDnHgVHG4I4YmxXr5D3Cdmcc7Yb2TG/zeB6qesdbWgRxhu2FPSRNs9HbOfjWqY/9qOiDyyyIjjxcCp/9/1TiKwu06xkopDBwFbnH1HpJ5TGxVuL9y7yuwcfOHLv0mRoWRG63vIlJIiTJWtEVrvpLxNxTl+/ph53OfSzwFfyi+dEoe/5UiSrsRo2yVfrPPNy08eWz+yMUB2TUCz2hxN61cjgQ2WJFCNNL4wG16z8jhFMne2IcyXuyatR5G9VIWXeSn0yEK8KudeyZhhkQMRGr2UMQdbDPnqwhCu7C6R6nUUH9d2laZj2hvrbaWdtkxxSdv478dQgxHvfBTuzftvZeavJ1cmeEZcJFMZGRqpxbDPkLnwynuEJkILIemXiFkgI3FZ2f5eoB34e98odp7QKYVI+xWf3edVXYtNV9E1DeEPYus46OGLR0BVZh4DYFr3V6DFN6/TmnKeq45ajFb+KGZ1b9BpL07ZQ2yQs6kGvUR6CYnBj8SUthtaqA12j/Xqf2+72slaFrkCt8zLQBEVskRgn+E6mfzEFlUyE0=
addons:
  apt:
    packages:
    - libzmq3-dev
before_install:
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update && brew install zeromq; fi
deploy:
  provider: script
  skip_cleanup: true
  script:
  - "./node_modules/prebuild/bin.js --target 8.6.0 --verbose --strip --upload ${GH_TOKEN}"
  on:
    condition: "$ZMQ_DYNAMIC = false"
    tags: true
